name: example
description: Aplikasi etalase (katalog) untuk menguji komponen TCoreUI.

# Cegah aplikasi example ini agar tidak tidak sengaja ter-publish ke pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Ini adalah kunci utamanya.
  # Kita memanggil package yang sedang kita buat menggunakan path relatif.
  # '../' berarti mundur satu folder (kembali ke root t_core_ui)
  tcoreui:
    path: ../

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true